export const route_names = {
  home: "home",
  sale: "sale",
  purchase: "purchase",
  newSale: "new-sale",
  saleHistory: "sale-history",
  customers: "customers",
  newPurchase: "new-purchase",
  purchaseHistory: "purchase-history",
  suppliers: "suppliers",
  products: "products",
  categories: "categories",
  stockManagement: "stock-management",
  employees: "employees",
  reports: "reports",
  saleReport: "sale-report",
  inventoryReport: "inventory-report",
  finanacialReport: "finanacial-report",
  setting: "setting",
};
